### ISSUE TITLE
Downloaded Courses

### ISSUE THREAD

**Issue by jfbserrano** [Chillee/coursera-dl-all#10]
Hi, Nice program here!

Just one thing, I'm not being able to choose the courses it downloads. Can I specify the courses I want? Or is it random?

Thanks!!

**Comment by Chillee** [comment]
Oh haha that would be hilarious if it was random :)

However, it's actually controlled by the courses in classes.csv

So if your classes.csv is

```
introstats-003
einstein-001
automata-004
```

Then you'll try to download those 3 classes.

**Comment by jfbserrano** [comment]
Hi, sorry 4 ur time i was dumb ^^ , i didnt read that part
thanks again and nice program!!

**Comment by jfbserrano** [comment]
one more thing, does it have the answers to the quizzes?

**Comment by Chillee** [comment]
Unluckily, for most courses, there doesn't appear to be a way to obtain the answers. I would if I could, but the site limits me from doing so.

**Comment by jfbserrano** [comment]
thanks again!
