### ISSUE TITLE
could you write the instruction step by step for dummy?

### ISSUE THREAD

**Issue by jerryxx** [Chillee/coursera-dl-all#11]
Thanks for the awesome code. Do we still have to download answer keys manually?

**Comment by lightbrush** [comment]
1. Install Firefox 46.
2. Install Python3
3. Install [cousera_dl](https://github.com/coursera-dl/coursera-dl) with pip if you want to download videos.
4. Download this repo as zip
5. Unzip the file to your preferred location.
6. Fill in the`classes.csv` file with your course ID and save.
7. open CMD and change your directory to the `dl_all.py` location. for example:
   
   ```
   cd F:\coursera-dl-all-master\coursera-dl-all-master
   ```
8. Write command like:
   
   ```
   python dl_all.py -u your_coursera_account -p your_password  -v(download video) -a(download assignment) -q(download quiz) --path the_location_of_download
   ```
   
   DONE

**Comment by jerryxx** [comment]
thanks
