### ISSUE TITLE
different errors when attempting to run in 2 different ways

### ISSUE THREAD

**Issue by nimad** [Chillee/coursera-dl-all#12]
On a Mac OS X, I tried things two ways and got different errors:

python dl_all.py -u myemail -q -a -p mypassword --headless

resulted in 
('https://class.coursera.org/molevol-003/', 'molevol-003')
Logging In....
Traceback (most recent call last):
  File "dl_all.py", line 280, in <module>
    error = login(session, class_url, args.u, args.p )
  File "dl_all.py", line 52, in login
    x.send_keys(email)
.....
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data

python dl_all.py -u myemail -q -a -p mypassword
resulted in:
('https://class.coursera.org/molevol-003/', 'molevol-003')
Traceback (most recent call last):
  File "dl_all.py", line 278, in <module>
    session = webdriver.Firefox()
....
ValueError: insecure string pickle

any thoughts?

**Comment by Chillee** [comment]
Do you have some strange characters in your username / password by any chance?

**Comment by nimad** [comment]
nope

**Comment by Chillee** [comment]
This project has been deprecated for a while. Just doing some cleaning.
