### ISSUE TITLE
Are you able to download Assignments/Quizzes ?

### ISSUE THREAD

**Issue by ChristosChristofidis** [Chillee/coursera-dl-all#17]
Using -v -a -q and still the only thing I see inside are folders with videos/slides/subtitles on Ubuntu 14.04 with Python 2.7 

In which operating system was the library tested ?

Running headless gets stuck on login screen. PhantomJS installed.

**Comment by Chillee** [comment]
This project has been deprecated for a while. Just doing some cleaning.
