### ISSUE TITLE
Stuck at logging in

### ISSUE THREAD

**Issue by nguyenminhduc9988** [Chillee/coursera-dl-all#5]
When I run the code it always stuck at the log in line. The credential is correct yet it still stuck. I just want to download the quiz of neural net.

**Comment by Chillee** [comment]
It works fine for me. Does it work for other courses?

Try taking a look at the browser while it's running. What appears to happen?

**Comment by Chillee** [comment]
I haven't been able to replicate this issue and I haven't heard it from anybody else.
