### ISSUE TITLE
No Quiz and Assignments for comparch-003

### ISSUE THREAD

**Issue by asarfraaz** [Chillee/coursera-dl-all#9]
I don't see any files downloaded for Quizes and Assignments for comparch-003

The screen output for assignments download is as below : [ removed username and password in the output below ]

$ python coursera-dl-all/dl_all.py -u yyy -p xxx  -a
https://class.coursera.org/comparch-003/ comparch-003
Logging In....
Logged in!
[]

$ ls coursera-downloads/comparch-003/assignments/
$

**Comment by Chillee** [comment]
If you look at the structure for comparch-003, you'll see that all the assignments are on the wiki page "Problem Sets"

Looking in the directory coursera-downloads/comparch-003/ should get you the assignments you're looking for.

**Comment by asarfraaz** [comment]
Ok, thanks. I must have confused myself with "Assessment" and "Assignment".

Does your script take care of downloading the "Assessments" as well ? For this course, they are present here : https://class.coursera.org/comparch-003/human_grading/view/courses/971875/assessments/23/submissions
